--[[
	One-Horn Cyclops armor for R15 characters (server Script).
	Generated by onehorn/build_onehorn.py - edit the settings, not the table.

	Setup:
		ReplicatedStorage
		└─ OneHornArmor (Folder)    <- every imported MeshPart from onehorn_armor.fbx
		ServerScriptService
		└─ OneHornArmor (Script)    <- this file

	Each MeshPart is named "<R15 body part>_Armor" or "<R15 body part>_Glow" and is
	welded onto the body part with that name, so it moves with normal R15 animations.
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

-- Settings ------------------------------------------------------------------
local APPLY_TO_PLAYERS = true -- every player spawns as the One-Horn Cyclops
local PREVIEW_MODEL_NAME = "OneHornCyclops" -- an R15 rig in Workspace with this name gets dressed too
local FLIP_180 = false -- set true if the armor shows up facing backwards
local STRIP_AVATAR = true -- remove hats/hair/clothes/face so they don't poke through
local BODY_COLOR = Color3.fromRGB(28, 27, 31)
local GLOW_COLOR = Color3.fromRGB(176, 70, 255)

-- Size and offset of each piece relative to its body part (R15 Block rig, studs).
local PIECES = {
--@@PIECES@@
}

-- R15 Block rig part sizes the armor was modelled on. Other body shapes get
-- the armor stretched per axis to fit.
local BLOCK_SIZE = {
--@@R15SIZES@@
}

-------------------------------------------------------------------------------
local armorFolder = ReplicatedStorage:WaitForChild("OneHornArmor")
local flip = FLIP_180 and CFrame.Angles(0, math.pi, 0) or CFrame.identity

local function partScale(bodyPart)
	if bodyPart.Name == "Head" then
		return Vector3.one
	end
	local block = BLOCK_SIZE[bodyPart.Name]
	return block and bodyPart.Size / block or Vector3.one
end

local function stripAvatar(character)
	for _, item in character:GetChildren() do
		if item:IsA("Accessory") or item:IsA("Clothing") or item:IsA("ShirtGraphic")
			or item:IsA("BodyColors") then
			item:Destroy()
		end
	end
	local head = character:FindFirstChild("Head")
	local face = head and head:FindFirstChildOfClass("Decal")
	if face then
		face:Destroy()
	end
	for name in BLOCK_SIZE do
		local part = character:FindFirstChild(name)
		if part and part:IsA("BasePart") then
			part.Color = BODY_COLOR
		end
	end
end

local function dress(character)
	if not character:FindFirstChild("UpperTorso") or character:FindFirstChild("OneHornArmorPieces") then
		return -- not R15, or already dressed
	end
	if STRIP_AVATAR then
		stripAvatar(character)
	end

	local holder = Instance.new("Folder")
	holder.Name = "OneHornArmorPieces"
	holder.Parent = character

	for _, template in armorFolder:GetChildren() do
		local info = PIECES[template.Name]
		local partName = string.match(template.Name, "^(%w+)_")
		local bodyPart = partName and character:FindFirstChild(partName)
		if not (info and bodyPart and template:IsA("BasePart")) then
			continue
		end

		local scale = partScale(bodyPart)
		local piece = template:Clone()
		piece.Anchored = false
		piece.CanCollide = false
		piece.CanQuery = false
		piece.CanTouch = false
		piece.Massless = true
		-- Setting Size also fixes any unit/scale mismatch from the import.
		piece.Size = info.size * scale
		piece.CFrame = bodyPart.CFrame * flip * CFrame.new(info.offset * scale)

		if string.match(template.Name, "_Glow$") then
			piece.TextureID = ""
			piece.Material = Enum.Material.Neon
			piece.Color = GLOW_COLOR
			if partName == "Head" or partName == "UpperTorso" then
				local light = Instance.new("PointLight")
				light.Color = GLOW_COLOR
				light.Brightness = 1.5
				light.Range = 8
				light.Parent = piece
			end
		end

		local weld = Instance.new("WeldConstraint")
		weld.Part0 = bodyPart
		weld.Part1 = piece
		weld.Parent = piece
		piece.Parent = holder
	end
end

if APPLY_TO_PLAYERS then
	local function onPlayer(player)
		player.CharacterAppearanceLoaded:Connect(dress)
		if player.Character then
			dress(player.Character)
		end
	end
	Players.PlayerAdded:Connect(onPlayer)
	for _, player in Players:GetPlayers() do
		onPlayer(player)
	end
end

local preview = workspace:FindFirstChild(PREVIEW_MODEL_NAME)
if preview then
	dress(preview)
end
