--[[
	One-Horn Cyclops armor for R15 characters (server Script).
	Generated by onehorn/build_onehorn.py - edit the settings, not the table.

	Setup:
		ReplicatedStorage
		└─ OneHornArmor (Folder)    <- every imported MeshPart from onehorn_armor.fbx
		ServerScriptService
		└─ OneHornArmor (Script)    <- this file

	Each MeshPart is named "<R15 body part>_Armor" or "<R15 body part>_Glow" and is
	welded onto the body part with that name, so it moves with normal R15 animations.
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

-- Settings ------------------------------------------------------------------
local APPLY_TO_PLAYERS = true -- every player spawns as the One-Horn Cyclops
local PREVIEW_MODEL_NAME = "OneHornCyclops" -- an R15 rig in Workspace with this name gets dressed too
local FLIP_180 = false -- set true if the armor shows up facing backwards
local STRIP_AVATAR = true -- remove hats/hair/clothes/face so they don't poke through
local BODY_COLOR = Color3.fromRGB(28, 27, 31)
local GLOW_COLOR = Color3.fromRGB(176, 70, 255)

-- Size and offset of each piece relative to its body part (R15 Block rig, studs).
local PIECES = {
	["Head_Armor"] = { size = Vector3.new(2.0028, 2.9261, 1.8561), offset = Vector3.new(-0.0000, 0.6348, 0.0181) },
	["Head_Glow"] = { size = Vector3.new(1.1921, 1.0575, 1.3105), offset = Vector3.new(-0.3460, 0.4432, -0.2447) },
	["LeftFoot_Armor"] = { size = Vector3.new(1.2400, 0.5653, 1.7967), offset = Vector3.new(-0.0000, -0.0027, -0.2783) },
	["LeftHand_Armor"] = { size = Vector3.new(1.4200, 0.5200, 1.4200), offset = Vector3.new(-0.0000, 0.0400, 0.0000) },
	["LeftHand_Glow"] = { size = Vector3.new(0.3631, 0.3373, 0.5732), offset = Vector3.new(-0.7026, 0.0875, -0.0628) },
	["LeftLowerArm_Armor"] = { size = Vector3.new(1.3300, 1.2177, 1.7722), offset = Vector3.new(-0.0150, 0.0488, 0.2061) },
	["LeftLowerArm_Glow"] = { size = Vector3.new(1.2692, 1.2261, 1.4199), offset = Vector3.new(-0.5194, 0.1100, 0.2806) },
	["LeftLowerLeg_Armor"] = { size = Vector3.new(1.2400, 1.3650, 1.7182), offset = Vector3.new(-0.0000, 0.0675, -0.2391) },
	["LeftUpperArm_Armor"] = { size = Vector3.new(1.8438, 1.5000, 1.8613), offset = Vector3.new(-0.1819, 0.1300, 0.0000) },
	["LeftUpperArm_Glow"] = { size = Vector3.new(1.1535, 1.8375, 1.1231), offset = Vector3.new(-0.8079, 0.8051, -0.0355) },
	["LeftUpperLeg_Armor"] = { size = Vector3.new(1.3100, 1.1500, 1.3553), offset = Vector3.new(-0.0250, 0.0250, -0.0477) },
	["LowerTorso_Armor"] = { size = Vector3.new(2.6502, 2.4200, 1.6000), offset = Vector3.new(-0.0000, -0.9900, 0.0000) },
	["RightFoot_Armor"] = { size = Vector3.new(1.2400, 0.5653, 1.7967), offset = Vector3.new(-0.0000, -0.0027, -0.2783) },
	["RightHand_Armor"] = { size = Vector3.new(1.4200, 0.5200, 1.4200), offset = Vector3.new(-0.0000, 0.0400, 0.0000) },
	["RightLowerArm_Armor"] = { size = Vector3.new(1.3300, 1.2177, 1.7722), offset = Vector3.new(0.0150, 0.0488, 0.2061) },
	["RightLowerLeg_Armor"] = { size = Vector3.new(1.2400, 1.3650, 1.7182), offset = Vector3.new(-0.0000, 0.0675, -0.2391) },
	["RightUpperArm_Armor"] = { size = Vector3.new(1.8438, 1.9063, 1.8613), offset = Vector3.new(0.1819, 0.3332, 0.0000) },
	["RightUpperLeg_Armor"] = { size = Vector3.new(1.3100, 1.1500, 1.3553), offset = Vector3.new(0.0250, 0.0250, -0.0477) },
	["UpperTorso_Armor"] = { size = Vector3.new(2.3000, 2.5678, 1.7250), offset = Vector3.new(-0.0000, -0.2161, 0.0675) },
	["UpperTorso_Glow"] = { size = Vector3.new(1.4692, 1.2034, 0.2066), offset = Vector3.new(-0.2514, 0.1667, -0.8012) },
}

-- R15 Block rig part sizes the armor was modelled on. Other body shapes get
-- the armor stretched per axis to fit.
local BLOCK_SIZE = {
	Head = Vector3.new(1.2, 1.2, 1.2),
	UpperTorso = Vector3.new(2, 1.6, 1),
	LowerTorso = Vector3.new(2, 0.4, 1),
	LeftUpperArm = Vector3.new(1, 1.169, 1),
	LeftLowerArm = Vector3.new(1, 1.052, 1),
	LeftHand = Vector3.new(1, 0.3, 1),
	RightUpperArm = Vector3.new(1, 1.169, 1),
	RightLowerArm = Vector3.new(1, 1.052, 1),
	RightHand = Vector3.new(1, 0.3, 1),
	LeftUpperLeg = Vector3.new(1, 1.217, 1),
	LeftLowerLeg = Vector3.new(1, 1.193, 1),
	LeftFoot = Vector3.new(1, 0.4, 1),
	RightUpperLeg = Vector3.new(1, 1.217, 1),
	RightLowerLeg = Vector3.new(1, 1.193, 1),
	RightFoot = Vector3.new(1, 0.4, 1),
}

-------------------------------------------------------------------------------
local armorFolder = ReplicatedStorage:WaitForChild("OneHornArmor")
local flip = FLIP_180 and CFrame.Angles(0, math.pi, 0) or CFrame.identity

local function partScale(bodyPart)
	if bodyPart.Name == "Head" then
		return Vector3.one
	end
	local block = BLOCK_SIZE[bodyPart.Name]
	return block and bodyPart.Size / block or Vector3.one
end

local function stripAvatar(character)
	for _, item in character:GetChildren() do
		if item:IsA("Accessory") or item:IsA("Clothing") or item:IsA("ShirtGraphic")
			or item:IsA("BodyColors") then
			item:Destroy()
		end
	end
	local head = character:FindFirstChild("Head")
	local face = head and head:FindFirstChildOfClass("Decal")
	if face then
		face:Destroy()
	end
	for name in BLOCK_SIZE do
		local part = character:FindFirstChild(name)
		if part and part:IsA("BasePart") then
			part.Color = BODY_COLOR
		end
	end
end

local function dress(character)
	if not character:FindFirstChild("UpperTorso") or character:FindFirstChild("OneHornArmorPieces") then
		return -- not R15, or already dressed
	end
	if STRIP_AVATAR then
		stripAvatar(character)
	end

	local holder = Instance.new("Folder")
	holder.Name = "OneHornArmorPieces"
	holder.Parent = character

	for _, template in armorFolder:GetChildren() do
		local info = PIECES[template.Name]
		local partName = string.match(template.Name, "^(%w+)_")
		local bodyPart = partName and character:FindFirstChild(partName)
		if not (info and bodyPart and template:IsA("BasePart")) then
			continue
		end

		local scale = partScale(bodyPart)
		local piece = template:Clone()
		piece.Anchored = false
		piece.CanCollide = false
		piece.CanQuery = false
		piece.CanTouch = false
		piece.Massless = true
		-- Setting Size also fixes any unit/scale mismatch from the import.
		piece.Size = info.size * scale
		piece.CFrame = bodyPart.CFrame * flip * CFrame.new(info.offset * scale)

		if string.match(template.Name, "_Glow$") then
			piece.TextureID = ""
			piece.Material = Enum.Material.Neon
			piece.Color = GLOW_COLOR
			if partName == "Head" or partName == "UpperTorso" then
				local light = Instance.new("PointLight")
				light.Color = GLOW_COLOR
				light.Brightness = 1.5
				light.Range = 8
				light.Parent = piece
			end
		end

		local weld = Instance.new("WeldConstraint")
		weld.Part0 = bodyPart
		weld.Part1 = piece
		weld.Parent = piece
		piece.Parent = holder
	end
end

if APPLY_TO_PLAYERS then
	local function onPlayer(player)
		player.CharacterAppearanceLoaded:Connect(dress)
		if player.Character then
			dress(player.Character)
		end
	end
	Players.PlayerAdded:Connect(onPlayer)
	for _, player in Players:GetPlayers() do
		onPlayer(player)
	end
end

local preview = workspace:FindFirstChild(PREVIEW_MODEL_NAME)
if preview then
	dress(preview)
end
