"""Build the whole corrupted-cyclops roster for Roblox.

Run:  python3 cyclops/build_all.py [--no-render]     (needs `pip install bpy==4.2.0 pillow`)

Outputs
  export/cyclops_texture.png        shared 1024 px texture atlas (also embedded in every FBX)
  export/outfits/<Outfit>.fbx       R15 outfit pieces named <R15Part>_<Kind>
  export/weapons/<Weapon>.fbx       weapon parts (Handle + others)
  (wolves: see wolf_rig.py -> export/creatures/)
  roblox/CyclopsData.lua            generated sizes/offsets/joints for every model
  renders/*.png                     preview lineups
"""
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import bpy  # noqa: E402
from mathutils import Matrix, Vector  # noqa: E402

import kit  # noqa: E402
from kit import R15_POS, R15_SIZE, Piece, export_fbx, lua_vec, piece_bounds  # noqa: E402

EXPORT_DIR = os.path.join(HERE, "export")
RENDER_DIR = os.path.join(HERE, "renders")
ROBLOX_DIR = os.path.join(HERE, "roblox")


def make_materials(img):
    def mat(name, emission):
        m = bpy.data.materials.new(name)
        m.use_nodes = True
        nodes = m.node_tree.nodes
        bsdf = nodes["Principled BSDF"]
        tex = nodes.new("ShaderNodeTexImage")
        tex.image = img
        m.node_tree.links.new(tex.outputs["Color"], bsdf.inputs["Base Color"])
        bsdf.inputs["Metallic"].default_value = 0.0 if emission else 0.3
        bsdf.inputs["Roughness"].default_value = 0.6
        if emission:
            m.node_tree.links.new(tex.outputs["Color"], bsdf.inputs["Emission Color"])
            bsdf.inputs["Emission Strength"].default_value = 4.0
        return m
    return mat("Cyclops", False), mat("CyclopsGlow", True)


# ---------------------------------------------------------------------------
def build_outfit_objects(outfit, mats):
    objs = []
    for part, kinds in outfit.pieces.items():
        for kind, piece in kinds.items():
            if not len(piece.bm.faces):
                piece.bm.free()
                continue
            mat = mats[1] if kind.endswith("Glow") else mats[0]
            obj = piece.to_object(f"{part}_{kind}", mat, R15_POS[part])
            obj["outfit"] = outfit.name
            objs.append(obj)
    return objs


def release_names(objs, prefix):
    """Rename exported objects so the next model can reuse the exact piece names
    (Blender would otherwise export "Head_Armor.001")."""
    for o in objs:
        o.name = f"{prefix}:{o.name}"
        o.data.name = o.name


def lua_color(rgb):
    return f"Color3.fromRGB({rgb[0]}, {rgb[1]}, {rgb[2]})"


def lua_outfit(outfit, objs):
    lines = [f'\t\t{outfit.name} = {{', f'\t\t\tglow = {lua_color(outfit.glow)},', '\t\t\tpieces = {']
    for o in sorted(objs, key=lambda o: o.name):
        size, offset = piece_bounds(o)
        lines.append(f'\t\t\t\t["{o.name}"] = {{ size = {lua_vec(size)}, offset = {lua_vec(offset)} }},')
    lines += ['\t\t\t},', '\t\t},']
    return "\n".join(lines)


def lua_weapon(weapon, objs):
    lines = [f'\t\t{weapon.name} = {{',
             f'\t\t\tdamage = {weapon.damage}, cooldown = {weapon.cooldown}, twoHanded = {str(weapon.two_handed).lower()},'
             f' bleed = {str(getattr(weapon, "bleed", False)).lower()},',
             f'\t\t\tglow = {lua_color(weapon.glow)},',
             f'\t\t\tgrip = CFrame.Angles({", ".join(f"math.rad({a})" for a in weapon.grip)}),',
             '\t\t\tpieces = {']
    for o in sorted(objs, key=lambda o: o.name):
        size, offset = piece_bounds(o)
        lines.append(f'\t\t\t\t["{o.name}"] = {{ size = {lua_vec(size)}, offset = {lua_vec(offset)} }},')
    lines += ['\t\t\t},', '\t\t},']
    return "\n".join(lines)


def write_data(outfit_lua, weapon_lua, creature_lua):
    sizes = "\n".join(f'\t\t{name} = Vector3.new({", ".join(f"{v:g}" for v in s)}),'
                      for name, s in R15_SIZE.items())
    text = f"""-- Generated by cyclops/build_all.py - do not edit by hand.
-- Sizes/offsets are in studs, relative to the R15 body part (outfits), the weapon's
-- grip origin (weapons) or the creature's origin (creatures).
return {{
\tblockSize = {{
{sizes}
\t}},
\toutfits = {{
{chr(10).join(outfit_lua)}
\t}},
\tweapons = {{
{chr(10).join(weapon_lua)}
\t}},
\tcreatures = {{
{chr(10).join(creature_lua)}
\t}},
}}
"""
    with open(os.path.join(ROBLOX_DIR, "CyclopsData.lua"), "w") as fh:
        fh.write(text)


# ---------------------------------------------------------------------------
# Preview rendering
def body_objects(mat, offset, scale=1.0):
    objs = []
    for part, (sx, sy, sz) in R15_SIZE.items():
        p = Piece()
        p.box((sx, sz, sy), "body")
        o = p.to_object("Body_" + part, mat, R15_POS[part])
        objs.append(o)
    place(objs, offset, scale)
    return objs


def place(objs, offset, scale=1.0, rot_z=0.0):
    bpy.context.view_layer.update()  # make matrix_world reflect freshly set locations
    m = (Matrix.Translation(offset) @ Matrix.Rotation(math.radians(rot_z), 4, "Z")
         @ Matrix.Scale(scale, 4))
    for o in objs:
        o.matrix_world = m @ o.matrix_world


def setup_scene():
    scene = bpy.context.scene
    scene.render.engine = "CYCLES"
    scene.cycles.device = "CPU"
    scene.cycles.samples = 32
    scene.cycles.use_denoising = True
    world = bpy.data.worlds.new("World")
    world.use_nodes = True
    bg = world.node_tree.nodes["Background"]
    bg.inputs["Color"].default_value = (0.1, 0.1, 0.11, 1)
    scene.world = world
    for name, loc, energy, size in (("Key", (-8, -14, 14), 5200, 10), ("Fill", (14, -8, 6), 1400, 10),
                                    ("Rim", (0, 14, 10), 3500, 10)):
        light = bpy.data.lights.new(name, "AREA")
        light.energy, light.size = energy, size
        obj = bpy.data.objects.new(name, light)
        obj.location = loc
        obj.rotation_euler = (Vector((0, 0, 3)) - Vector(loc)).to_track_quat("-Z", "Y").to_euler()
        scene.collection.objects.link(obj)
    cam = bpy.data.cameras.new("Camera")
    cam.type = "ORTHO"
    cam_obj = bpy.data.objects.new("Camera", cam)
    scene.collection.objects.link(cam_obj)
    scene.camera = cam_obj
    return scene, cam_obj


def render(scene, cam, path, loc, target, scale, res):
    cam.location = loc
    cam.rotation_euler = (Vector(target) - Vector(loc)).to_track_quat("-Z", "Y").to_euler()
    cam.data.ortho_scale = scale
    scene.render.resolution_x, scene.render.resolution_y = res
    scene.render.filepath = path
    bpy.ops.render.render(write_still=True)


def set_visible(all_objs, visible):
    keep = set(map(id, visible))
    for o in all_objs:
        if o.type == "MESH":
            o.hide_render = id(o) not in keep


# ---------------------------------------------------------------------------
WEAPON_OF = {
    "Villager": "Pitchfork", "Hunter": "HunterBow", "Woodcutter": "WoodcutterAxe",
    "WolfRider": "WolfRiderSpear", "KnightApprentice": "ApprenticeSword",
    "EliteOneHorn": "OneHornGreatsword", "KnightApprenticeInfected": "ApprenticeAxe",
    "KnightMid": "MidSword", "KnightHigh": "HighAxe",
}
SIDEWAYS = {"HunterBow", "WoodcutterAxe", "ApprenticeAxe", "MidAxe", "HighAxe"}


def build_weapon_objects(weapon, mats):
    objs = []
    for kind, piece in weapon.pieces.items():
        mat = mats[1] if kind.endswith("Glow") else mats[0]
        objs.append(piece.to_object(kind, mat, (0, 0, 0)))
    return objs


def main():
    no_render = "--no-render" in sys.argv
    bpy.ops.wm.read_factory_settings(use_empty=True)
    bpy.context.preferences.filepaths.save_version = 0
    for d in (EXPORT_DIR, RENDER_DIR, ROBLOX_DIR):
        os.makedirs(d, exist_ok=True)
    img = bpy.data.images.load(kit.build_atlas(os.path.join(EXPORT_DIR, "cyclops_texture.png")))
    mats = make_materials(img)

    import weapons
    from outfits import elite, king, knights, stage1
    groups = {
        "stage1": stage1.all_stage1() + [knights.apprentice("KnightApprentice", 0.3, 21), elite.elite_onehorn()],
        "stage2": knights.all_knights()[1:],
        "boss": [king.cyclops_king()],
    }
    outfits = [o for g in groups.values() for o in g]

    outfit_lua, weapon_lua, creature_lua = [], [], []
    outfit_objs, weapon_objs, creature_objs = {}, {}, {}
    for outfit in outfits:
        objs = build_outfit_objects(outfit, mats)
        export_fbx(os.path.join(EXPORT_DIR, "outfits", outfit.name + ".fbx"), objs)
        outfit_lua.append(lua_outfit(outfit, objs))
        release_names(objs, outfit.name)
        outfit_objs[outfit.name] = objs
        print(f"{outfit.name}: {len(objs)} pieces, {sum(len(o.data.polygons) for o in objs)} faces")
    for weapon in weapons.all_weapons():
        objs = build_weapon_objects(weapon, mats)
        export_fbx(os.path.join(EXPORT_DIR, "weapons", weapon.name + ".fbx"), objs)
        weapon_lua.append(lua_weapon(weapon, objs))
        release_names(objs, weapon.name)
        weapon_objs[weapon.name] = objs
        print(f"{weapon.name}: {len(objs)} parts, {sum(len(o.data.polygons) for o in objs)} faces")
    # Wolves are skinned rigs built by wolf_rig.py (export/creatures), not part of this build.
    write_data(outfit_lua, weapon_lua, creature_lua)
    bpy.ops.wm.save_as_mainfile(filepath=os.path.join(EXPORT_DIR, "cyclops_roster.blend"))
    if no_render:
        return
    render_previews(groups, outfit_objs, weapons, creature_objs, mats)


def held_weapon(weapons_mod, name, mats, hand_pos, scale):
    """A fresh copy of a weapon posed in the right hand, pointing forward and down."""
    w = {x.name: x for x in weapons_mod.all_weapons()}[name]
    objs = build_weapon_objects(w, mats)
    aim = Vector((-0.15, -0.8, -0.55)) if name not in ("HunterBow",) else Vector((0, -0.15, 1))
    rot = aim.to_track_quat("Z", "Y").to_matrix().to_4x4()
    bpy.context.view_layer.update()
    m = Matrix.Translation(hand_pos) @ Matrix.Scale(scale, 4) @ rot
    for o in objs:
        o.matrix_world = m
    return objs


def render_previews(groups, outfit_objs, weapons_mod, creature_objs, mats):
    scene, cam = setup_scene()
    scales = {"CyclopsKing": 1.6}
    parked = []
    for group, members in groups.items():
        shown, x = [], 0.0
        for outfit in members:
            k = scales.get(outfit.name, 1.0)
            offset = Vector((x + 2.3 * k, 0, 0))
            objs = outfit_objs[outfit.name]
            place(objs, offset, k)
            shown += objs + body_objects(mats[0], offset, k)
            if outfit.name in WEAPON_OF:
                hand = offset + Vector(R15_POS["RightHand"]) * k + Vector((0, -0.1, 0))
                shown += held_weapon(weapons_mod, WEAPON_OF[outfit.name], mats, hand, k)
            x += 4.6 * k
        set_visible(bpy.data.objects, shown)
        top = 6.8 * max(scales.get(o.name, 1.0) for o in members)
        center = (x / 2, 0, top / 2 - 0.1)
        if group == "boss":
            res, size = (1000, 1200), top + 1.8
            render(scene, cam, os.path.join(RENDER_DIR, "boss_hero.png"), (x / 2 - 9, -16, 10), (x / 2, 0, 6.6),
                   10.5, (1000, 1000))
        else:
            res = (1800, int(1800 * (top + 1.0) / (x + 0.6)))
            size = x + 0.6
        render(scene, cam, os.path.join(RENDER_DIR, f"{group}_front.png"), (center[0], -40, center[2]),
               center, size, res)
        render(scene, cam, os.path.join(RENDER_DIR, f"{group}_back.png"), (center[0], 40, center[2]),
               center, size, res)
        place(shown, Vector((0, 0, -100)))

    # Weapons laid out side by side, blade up.
    shown, x = [], 0.0
    for name, objs in weapons_mod_objs(weapons_mod, mats).items():
        place(objs, Vector((x, 0, 1.6)), 1.0, 90 if name in SIDEWAYS else 0)
        shown += objs
        x += 1.5
    set_visible(bpy.data.objects, shown)
    render(scene, cam, os.path.join(RENDER_DIR, "weapons.png"), ((x - 1.5) / 2, -40, 2.4),
           ((x - 1.5) / 2, 0, 2.4), x + 0.4, (1800, int(1800 * 6.0 / (x + 0.4))))
    place(shown, Vector((0, 0, -100)))



def weapons_mod_objs(weapons_mod, mats):
    return {w.name: build_weapon_objects(w, mats) for w in weapons_mod.all_weapons()}


if __name__ == "__main__":
    main()
